### PR TITLE
Fix confusion of sensors with SensorSocketAgent

### PR DESCRIPTION
**Pull request by maxmitti**
When SensorSocketAgent is used, calling writeMsg immediately triggers msgSent which calls executeCommand again. In the end the nested executeCommand call manages to enqueue its request to mProcessingFIFO before the request of the original call is enqueued.

Finally, when the response for the first sent command is received it is matched with the second command and vice-versa. This resulted in sensor labels getting mixed up.

### CODE REVIEW

**Comment by maxmitti** [comment]
I noticed this when setting up https://github.com/lestofante/ksysguard-gpu.
I loaded the provided sample Tab and modified it to my liking.

Finally, I closed KSysGuard and opened it again.
When the tab gets restored, the mix-up happens.

**Comment by zvova7890** [comment]
Looks reasonable. It's interesting why nobody mentioned that before in the Qt5 version ;/

**Comment by maxmitti** [comment]
It didn’t happen there. Probably because it used `QRegExp`.

**Comment by zvova7890** [comment]
@maxmitti I think you confused with `regexpSensorName`, didn't you?

**Comment by maxmitti** [comment]
Oh, yes. Sorry.

Regarding this one, I assume that the daemon (UI name for socket) variant was not used often enough.
In most cases stdio (possibly via ssh) makes more sense, at least in my opinion.

**Comment by zvova7890** [comment]
It seems you're right; there's QTcpSocket being used asynchronously, so there's a real chance of a race condition.

**Comment by zvova7890** [comment]
Thanks!

**Pull request merged**
