### PR TITLE
Add possibility to move tabs

### PR DESCRIPTION
**Pull request by Wabelbit**
I've been wanting to be able to reorder my tabs forever, so here's two buttons for the toolbar to do exactly that:
image

 I guess if we're already gonna keep this thing alive, now is as good a time as any to make it happen :D

### CODE REVIEW

**Comment by zvova7890** [comment]
I guess, why not?

I've compiled your PR, but I can't see these buttons in the Toolbar, only in the shortcuts settings. Is this ok?

Also, I think it is possible to enable and adapt a "movable" QTabBar, which means that it will be possible to reorder tabs with the mouse.

**Comment by Wabelbit** [comment]
The buttons can be added to the toolbar via KDE's common "Configure Toolsbars" option in KSysguard.
I kept it quick and simple for now as I wanted to keep the changes minimal, but I can look into making the tabs draggable to see how it feels. Sounds like a good idea and more intuitive from a UX point of view.

**Comment by zvova7890** [comment]
Ah, I see. I'm not a big fan of toolbars, so I didn't know about that :)

I think if we're going to be adding new features rather than just maintaining them, adding mouse tab reordering would be useful feature, and we can allow ourselves to do so without being restricted by the weight of changes.

**Comment by Wabelbit** [comment]
Okay, now I'm happy with it. Dragging tabs around with the mouse feels so good, shame I didn't do it 5 years ago already :D

**Comment by zvova7890** [comment]
I like it too!

Could you please rebase it and leave only changes related to the adding movable functionality?

**Comment by Wabelbit** [comment]
Sure, done!

**Comment by zvova7890** [comment]
Merged. Thanks!

**Pull request merged**
